### ISSUE TITLE
dockerを用いたphpの環境構築

### ISSUE THREAD

**Issue by k911672** [k911672/todo-php-docker2#1]
## dockerの設定
ファイルのインストールは省略

## 1. docker-compose.ymlの設定 
```
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % pwd
/Users/kimuranaoki/michael-php/todo-php/todo-php-docker
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % vim docker-compose.yml 
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % cat docker-compose.yml 
version: '3'
services:
  web:
    container_name: nginx-app
    image: nginx:1.15.6
    ports:
      - "8000:80"
    depends_on: 
      - app
    volumes:
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
  app:
    container_name: php-app
    build: ./docker/php
    volumes:
     - .:/var/www/html
    depends_on:
      - mysql
  mysql:
    container_name: mysql-app
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: common
      MYSQL_USER: michael
      MYSQL_PASSWORD: 11922960Kim@
      MYSQL_ROOT_PASSWORD: 11922960Kim@
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
volumes:
  mysql-data:
```

### 2. docker-composeの起動
```
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % docker-compose up -d
Docker Compose is now in the Docker CLI, try `docker compose up`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
WARNING: Image for service app was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating mysql-app ... done
Creating php-app   ... done
Creating nginx-app ... done
```

### 3. コンテナの起動確認
```
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % docker-compose ps
  Name                 Command              State              Ports            
--------------------------------------------------------------------------------
mysql-app   docker-entrypoint.sh mysqld     Up      0.0.0.0:3306->3306/tcp,:::33
                                                    06->3306/tcp, 33060/tcp     
nginx-app   nginx -g daemon off;            Up      0.0.0.0:8000->80/tcp,:::8000
                                                    ->80/tcp                    
php-app     docker-php-entrypoint php-fpm   Up      9000/tcp  
```
動いているコンテナだけ出てくる。

### コンテナをストップする場合
```
kimuranaoki@kimuranaokinoMacBook-Pro todo-php-docker % docker-compose down
Stopping nginx-app ... done
Stopping php-app   ... done
Stopping mysql-app ... done
Removing nginx-app ... done
Removing php-app   ... done
Removing mysql-app ... done
Removing network todo-php-docker_default
```

**Comment by k911672** [comment]
## dokcerの設定直し

インフラの勉強で習ったdocker-compose.ymlの設定を今回のphpの勉強に反映させてる。
```
version: '2'
services:
  web:
    container_name: app-php-todo
    build: ./app/
    image: app-php-todo
    ports:
      - "80:80"
    depends_on: 
      - mysql
    volumes:
      - ~/michael-php/todo-php/todo-php-docker:/var/www/app/
  mysql:
    container_name: mysql-php-todo
    build: ./mysql/
    image: mysql-php-todo
    environment:
      MYSQL_DATABASE: todo
      MYSQL_USER: naoki
      MYSQL_PASSWORD: 11922960Kim@
      MYSQL_ROOT_PASSWORD: 11922960Kim@
      TZ: "Asia/Tokyo"
    ports:
      - "3309:3306"
    volumes:
      - ~/michael-php/todo-php/todo-php-docker/docker/docker-php-todo/mysql/db-data:/var/lib/mysql
```

mysqlのデータの保存先は`docker-compose up -d`で自動で生成される
